name: Auditoría de Seguridad - Dependency-Check

on:
  push:
    branches: [ main, master, QA ]
  pull_request:
    branches: [ main, master, QA ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      - name: Ejecutar OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Dependency-Check
        continue-on-error: true
        with:
          project: 'Proyecto Monorepo QA - Grupo ${{ github.repository }}'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableNodeAudit
            --disablePnpmAudit

      - name: Subir Reporte de Vulnerabilidades como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-seguridad-owasp
          path: reports/dependency-check-report.html